backend:
  name: github
  repo: maria9956/ARSHiL
  branch: main
  base_url: https://api.netlify.com
  auth_endpoint: auth

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "home"
    label: "الصفحة الرئيسية"
    files:
      - label: "الصفحة الرئيسية"
        name: "homepage"
        file: "index.html"
        fields:
          - { label: "العنوان", name: "title", widget: "string" }
          - { label: "الوصف", name: "description", widget: "text" }

